Repository 42atomys/stud42, pull requests merged in 2022-12, with the labels that each got.

#290 fix: campus crawler don't update new values
  cmd/campus.go
Labels: state/triage 🚦, size/S

#291 feat(cluster)!: implement a new version of the clustermap system and add vienna maps
  cmd/locations.go
  web/ui/next.config.js
  web/ui/src/components/ClusterMap/ClusterContainer.tsx
  web/ui/src/components/ClusterMap/ClusterTableMap.tsx
  web/ui/src/components/ClusterMap/data.ts
  web/ui/src/components/ClusterMap/index.ts
  web/ui/src/components/ClusterMap/types.d.ts
  web/ui/src/containers/clusters/ClusterSidebar.tsx
  web/ui/src/lib/clustersMap/campus.ts
  web/ui/src/lib/clustersMap/campus/helsinki.ts
  web/ui/src/lib/clustersMap/campus/malaga.ts
  web/ui/src/lib/clustersMap/campus/paris.ts
  web/ui/src/lib/clustersMap/campus/vienna.ts
  web/ui/src/lib/clustersMap/cluster.ts
  web/ui/src/lib/clustersMap/index.ts
  web/ui/src/lib/clustersMap/types.d.ts
  web/ui/src/lib/searchEngine.ts
  web/ui/src/pages/clusters/[campusName]/[cluster].tsx
  web/ui/src/pages/clusters/helsinki/[cluster].tsx
  web/ui/src/pages/clusters/index.tsx
  web/ui/src/pages/clusters/malaga/[cluster].tsx
  web/ui/src/pages/clusters/paris/[cluster].tsx
Labels: size/XXL

#289 feat: integrate meilisearch as new searchengine
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yaml
  cmd/api.go
  cmd/campus.go
  cmd/locations.go
  cmd/operations.go
  cmd/reindexusers.go
  cmd/root.go
  cmd/webhooks.go
  deploy/modules/service/variables.tf
  deploy/stacks/apps/s42/api.tf
  deploy/stacks/apps/s42/crawlers.tf
  deploy/stacks/apps/s42/interface.tf
  deploy/stacks/apps/s42/jwtks_service.tf
  deploy/stacks/apps/s42/meilisearch.tf
  deploy/stacks/apps/s42/webhook_processor.tf
  go.mod
  go.sum
  internal/api/api.resolvers.go
  internal/models/client.go
  internal/models/schema/user.go
  internal/models/utils.go
  internal/pkg/searchengine/meilisearch.go
  internal/pkg/searchengine/meilisearch_user_index.go
  internal/pkg/searchengine/searchengine.go
  web/ui/src/components/Search/Search.tsx
Labels: state/triage 🚦, size/XL, needs-preview-deploy

#294 fix: missing c3 cluster data on vienna campus
  web/ui/src/lib/clustersMap/campus/vienna.ts
Labels: state/triage 🚦, size/S

#297 fix: operations reindex users reach max meilisearch connection
  cmd/reindexusers.go
Labels: state/triage 🚦, size/S

#302 fix: search engine order is not relevant
  cmd/locations.go
  cmd/reindexusers.go
  internal/api/api.resolvers.go
  internal/models/schema/user.go
  internal/pkg/searchengine/meilisearch.go
  internal/pkg/searchengine/meilisearch_user_index.go
  pkg/utils/slice.go
  pkg/utils/slice_test.go
Labels: state/triage 🚦, size/L

#303 fix: locations badge on friends page crash due to invalid location
  web/ui/src/components/Badge/LocationBadge.tsx
  web/ui/src/lib/clustersMap/campus.ts
  web/ui/src/lib/clustersMap/campus/helsinki.ts
  web/ui/src/lib/clustersMap/campus/malaga.ts
  web/ui/src/lib/clustersMap/campus/paris.ts
  web/ui/src/lib/clustersMap/campus/vienna.ts
  web/ui/src/lib/clustersMap/types.d.ts
Labels: state/triage 🚦, size/L

#307 fix: fixed row numbers seoul cluster c9 that were wrong
  web/ui/src/lib/clustersMap/campus/seoul.ts
Labels: size/XS

#299 chore: update devcontainers readme
  .devcontainer/devcontainer.json
  .vscode/tasks.json
  docs/devcontainers/README.md
Labels: aspect/documentation 📚, size/M

#306 feat: add support of mac m1 on devcontainers
  .devcontainer/Dockerfile
  build/Makefile
  build/install-dependencies.sh
  web/ui/package.json
  web/ui/yarn.lock
Labels: aspect/dex 🤖, size/M

#357 fix: meilisearch tasks is not cleaned and increase the volume size
  deploy/stacks/apps/s42/meilisearch.tf
Labels: size/M

#358 Typo + wording fix in README.md
  README.md
Labels: size/XS

#360 chore: upgrade nextjs to v13
  .devcontainer/Dockerfile
  .github/workflows/tests.yaml
  web/ui/next.config.js
  web/ui/package.json
  web/ui/src/components/AuthError/__tests__/AuthError.test.tsx
  web/ui/src/components/AuthError/__tests__/__snapshots__/AuthError.test.tsx.snap
  web/ui/src/components/Badge/Badge.tsx
  web/ui/src/components/Badge/LocationBadge.tsx
  web/ui/src/components/Badge/__tests__/Badge.test.tsx
  web/ui/src/components/Badge/__tests__/LocationBadge.test.tsx
  web/ui/src/components/Badge/__tests__/__snapshots__/Badge.test.tsx.snap
  web/ui/src/components/Badge/__tests__/__snapshots__/LocationBadge.test.tsx.snap
  web/ui/src/components/Badge/__tests__/countryMap.test.ts
  web/ui/src/components/Emoji/types.d.ts
  web/ui/src/components/Sidebar/Sidebar.tsx
  web/ui/src/components/Sidebar/SidebarMenu.tsx
  web/ui/src/containers/clusters/ClusterSidebar.tsx
  web/ui/src/lib/apollo.ts
  web/ui/src/pages/api/auth/[...nextauth].ts
  web/ui/yarn.lock
Labels: aspect/interface 🕹, size/XXL, needs-preview-deploy
