Repository 42atomys/stud42, pull requests merged in 2023-07, with the labels that each got.

#470 chore: upgrade monitoring stack major version
  deploy/stacks/cluster/configs/monitoring/loki.yaml
  deploy/stacks/cluster/configs/monitoring/tempo.yaml
  deploy/stacks/cluster/monitoring.tf
Labels: state/triage 🚦, size/M

#477 fix: twitch credentials invalid cause linking impossible
  deploy/stacks/apps/s42/secrets.tf
Labels: state/triage 🚦, size/XS

#481 chore: rotate forty two secret
  deploy/stacks/apps/s42/secrets.tf
Labels: state/triage 🚦, size/XS

#478 fix: paris campus locations regexp
  web/ui/src/components/Badge/__tests__/LocationBadge.test.tsx
  web/ui/src/components/Badge/__tests__/__snapshots__/LocationBadge.test.tsx.snap
  web/ui/src/lib/clustersMap/campus/paris.ts
  web/ui/src/lib/searchEngine.ts
Labels: priority/low 🟩, aspect/interface 🕹, domain/obvious 🟩, type/bug 🔥, size/S

#484 fix: deprecated main cursus has displayed first
  web/ui/src/components/UserProfile/UserProfile.tsx
Labels: state/confirmed 💜, priority/medium 🟨, aspect/interface 🕹, domain/obvious 🟩, type/bug 🔥, size/S

#490 feat: add all abouts and legals pages
  web/ui/src/components/Sidebar/SidebarMenu.tsx
  web/ui/src/components/Sidebar/types.d.ts
  web/ui/src/containers/settings/SettingsLayout.tsx
  web/ui/src/pages/about/help.tsx
  web/ui/src/pages/about/index.tsx
  web/ui/src/pages/about/privacy.tsx
  web/ui/src/pages/about/terms.tsx
  web/ui/src/pages/auth/signin.tsx
  web/ui/src/pages/settings/about.tsx
  web/ui/src/pages/settings/help.tsx
  web/ui/src/pages/settings/privacy.tsx
  web/ui/src/pages/settings/terms.tsx
Labels: state/triage 🚦, size/XL

#491 chore: remove phone features and data
  api/graphs/api.graphqls
  go.mod
  go.sum
  internal/api/api.resolvers.go
  internal/models/schema/user.go
  internal/models/utils.go
  internal/webhooks/user.go
  web/ui/src/graphql/definitions.gql
  web/ui/src/lib/GraphqlAdapter/graphql-adapter.ts
  web/ui/src/lib/GraphqlAdapter/types.d.ts
  web/ui/src/lib/auth.ts
Labels: state/triage 🚦, size/M

#493 chore: upgrade to postgres 15 and enable btree gin extension
  .devcontainer/docker-compose.yaml
  .github/workflows/packages.yaml
  build/packages/postgres/Dockerfile
  build/packages/postgres/extensions.sh
Labels: state/confirmed 💜, priority/high 🟧, aspect/dex 🤖, type/chore 🛠, domain/obvious 🟩, size/XS, aspect/infrastructure 🗄️

#494 perf: fetch locations per user id
  internal/models/schema/location.go
Labels: state/triage 🚦, size/XS

#492 fix: layout close profile on cluster map on each click
  web/ui/src/components/ClusterMap/ClusterContainer.tsx
  web/ui/src/components/ClusterMap/ClusterTableMap.tsx
  web/ui/src/components/UserPopup/UserPopup.tsx
  web/ui/src/components/UserPopup/types.d.ts
Labels: state/triage 🚦, size/M

#496 chore: upgrade to postgresql 15 in production
  deploy/stacks/apps/s42/storages.tf
Labels: state/triage 🚦, size/XS

#495 feat: download my data and send it by student email
  .devcontainer/postStartCommand.sh
  .vscode/settings.json
  cmd/exportdata.go
  config/stud42.example.yaml
  deploy/stacks/apps/configs/stud42/stud42.yaml.tftpl
  internal/pkg/s3/client.go
  web/ui/package.json
  web/ui/src/components/Button/Button.tsx
  web/ui/src/components/Button/index.ts
  web/ui/src/components/Button/types.d.ts
  web/ui/src/containers/settings/SettingsLayout.tsx
  web/ui/src/pages/settings/account.tsx
  web/ui/src/pages/settings/accounts.tsx
  web/ui/src/pages/settings/profile.tsx
  web/ui/tailwind.config.js
  web/ui/yarn.lock
Labels: state/triage 🚦, size/XL

#497 revert: postgres upgrade to version 15 rollbacked to 14.8
  .devcontainer/docker-compose.yaml
  build/packages/postgres/Dockerfile
  deploy/stacks/apps/s42/storages.tf
Labels: state/triage 🚦, size/XS

#485 feat: adding mulhouse campus
  web/ui/src/lib/clustersMap/campus/mulhouse.ts
  web/ui/src/lib/clustersMap/index.ts
  web/ui/src/lib/clustersMap/types.d.ts
Labels: size/M
