Repository 42atomys/stud42, pull requests merged in 2023-02, with the labels that each got.

#390 fix: issue has marked stale due to incorrect label name
  .github/workflows/issues.yaml
Labels: size/XS

#393 fix: install protoc in ci with setup-protoc to avoid rate-limiting by github
  .github/workflows/build.yaml
  .github/workflows/issues.yaml
  .github/workflows/linters.yaml
  .github/workflows/previews-cleaner.yaml
  .github/workflows/tests.yaml
Labels: priority/low 🟩, aspect/dex 🤖, domain/complicated 🟨, type/bug 🔥, size/M

#394 fix: duo time crash when unmarshalled value is null
  pkg/duoapi/time.go
  pkg/duoapi/time_test.go
Labels: state/triage 🚦, size/L

#396 fix: delete a location on cascade delete the associated user
  internal/models/schema/user.go
Labels: priority/critical 🟥, aspect/backend 💻, domain/complex 🟧, type/bug 🔥, size/XS

#395 chore: make requirement of the beta like star and follow more visible on beta access page
  web/ui/next.config.js
  web/ui/src/pages/beta/index.tsx
Labels: state/triage 🚦, size/M

#398 feat: integrate lausanne campus
  web/ui/src/lib/clustersMap/campus/lausanne.ts
  web/ui/src/lib/clustersMap/index.ts
  web/ui/src/lib/clustersMap/types.d.ts
Labels: size/M

#401 fix: stars cause multiples useless render
  web/ui/src/lib/github.tsx
  web/ui/src/lib/useSessionStorage.ts
Labels: state/triage 🚦, size/L
