Repository 42atomys/stud42, pull requests merged in 2023-06, with the labels that each got.

#457 fix: latency and white theme flickering caused by next-auth issues
  web/ui/package.json
  web/ui/src/contexts/currentUser.tsx
  web/ui/src/pages/_app.tsx
  web/ui/src/pages/api/auth/[...nextauth].ts
  web/ui/yarn.lock
Labels: state/triage 🚦, size/L

#458 feat: celebrating pride month 🏳️‍🌈
  web/ui/public/assets/images/logo_pride.svg
  web/ui/src/components/Sidebar/Sidebar.tsx
Labels: state/triage 🚦, size/M

#463 feat: add personal workspace entity on cluster map
  web/ui/src/components/ClusterMap/ClusterTableMap.tsx
  web/ui/src/components/ClusterMap/index.ts
  web/ui/src/lib/clustersMap/types.d.ts
  web/ui/src/pages/clusters/[campusName]/[cluster].tsx
Labels: size/M

#462 chore: migrate clusters map for paris campus to noc42
  .devcontainer/docker-compose.yaml
  go.mod
  go.sum
  internal/api/api.resolvers.go
  web/ui/src/components/Badge/__tests__/LocationBadge.test.tsx
  web/ui/src/components/Badge/__tests__/__snapshots__/LocationBadge.test.tsx.snap
  web/ui/src/containers/clusters/ClusterSidebar.tsx
  web/ui/src/graphql/definitions.gql
  web/ui/src/lib/clustersMap/campus.ts
  web/ui/src/lib/clustersMap/campus/paris.ts
  web/ui/src/lib/clustersMap/types.d.ts
  web/ui/src/pages/clusters/index.tsx
Labels: size/L

#465 feat: remote notice to announce things to final users
  api/graphs/api.graphqls
  cmd/api.go
  go.mod
  go.sum
  internal/api/api.resolvers.go
  internal/models/gotype/notice_color.go
  internal/models/schema/notice.go
  internal/models/schema/notice_user.go
  internal/models/schema/user.go
  web/ui/src/components/Notice/Notice.tsx
  web/ui/src/components/Notice/RemoteNotices.tsx
  web/ui/src/components/Notice/index.ts
  web/ui/src/components/Notice/types.d.ts
  web/ui/src/components/Sidebar/Sidebar.tsx
  web/ui/src/graphql/definitions.gql
  web/ui/src/lib/storageKeys.ts
Labels: type/feature ⭐, aspect/interface 🕹, size/L

#467 fix: theme are blinking on first page load
  web/ui/package.json
  web/ui/src/contexts/currentUser.tsx
  web/ui/src/pages/_app.tsx
  web/ui/yarn.lock
Labels: state/triage 🚦, size/M

#468 refactor: change some behavior of github workflows
  .github/workflows/ci.yaml
  .github/workflows/discord-push-release.yaml
  .github/workflows/tests.yaml
Labels: state/triage 🚦, size/S

#469 fix: colors mismatch on themes
  web/ui/src/components/Form/FileInput.tsx
  web/ui/src/components/Form/SelectInput.tsx
  web/ui/src/components/Search/Search.tsx
  web/ui/src/components/Sidebar/Sidebar.tsx
  web/ui/src/components/Sidebar/SidebarMenu.tsx
  web/ui/src/containers/settings/SettingsCategory.tsx
  web/ui/src/lib/github.tsx
  web/ui/src/pages/_document.tsx
  web/ui/src/pages/friends/[groupSlug].tsx
  web/ui/src/pages/settings/accounts.tsx
Labels: state/triage 🚦, size/M
