Repository 42atomys/stud42, pull requests merged in 2023-01, with the labels that each got.

#372 fix: time in the past on badge tests to prevent false errors
  .gitignore
  .vscode/tasks.json
  build/install-dependencies.sh
  web/ui/src/components/Badge/__tests__/LocationBadge.test.tsx
  web/ui/src/components/Badge/__tests__/__snapshots__/LocationBadge.test.tsx.snap
Labels: state/triage 🚦, size/M

#373 fix: mismatch between campus data and intra data
  web/ui/src/lib/clustersMap/campus/seoul.ts
Labels: size/XS

#374 chore: disable ci on tags
  .github/workflows/ci.yaml
Labels: size/XS

#380 fix: bump loki storage
  deploy/stacks/cluster/monitoring.tf
Labels: state/triage 🚦, size/XS
