Repository 42atomys/stud42, pull requests merged in 2023-10, with the labels that each got.

#528 fix: correct paul cluster seats and names, add add cluster names in paris
  go.mod
  go.sum
  web/ui/src/lib/clustersMap/campus/paris.ts
Labels: size/M

#376 feat: integrate wolfsburg campus #359
  web/ui/src/lib/clustersMap/campus/wolfsburg.ts
  web/ui/src/lib/clustersMap/index.ts
  web/ui/src/lib/clustersMap/types.d.ts
Labels: type/improvement ✨, state/needs information 🚧, aspect/interface 🕹, stale/unstale 🍖, domain/obvious 🟩, size/M

#529 Adding madrid cluster map
  web/ui/src/lib/clustersMap/campus/madrid.ts
  web/ui/src/lib/clustersMap/index.ts
  web/ui/src/lib/clustersMap/types.d.ts
Labels: size/M

#530 refactor: campus management with generators
  web/ui/generators/generateCampusTypes.ts
  web/ui/jest.setup.ts
  web/ui/package.json
  web/ui/src/components/ClusterMap/ClusterContainer.tsx
  web/ui/src/components/ClusterMap/types.d.ts
  web/ui/src/components/Search/Search.tsx
  web/ui/src/containers/clusters/ClusterSidebar.tsx
  web/ui/src/lib/clustersMap/campus.ts
  web/ui/src/lib/clustersMap/campus/helsinki.ts
  web/ui/src/lib/clustersMap/campus/lausanne.ts
  web/ui/src/lib/clustersMap/campus/madrid.ts
  web/ui/src/lib/clustersMap/campus/malaga.ts
  web/ui/src/lib/clustersMap/campus/mulhouse.ts
  web/ui/src/lib/clustersMap/campus/paris.ts
  web/ui/src/lib/clustersMap/campus/seoul.ts
  web/ui/src/lib/clustersMap/campus/tokyo.ts
  web/ui/src/lib/clustersMap/campus/vienna.ts
  web/ui/src/lib/clustersMap/campus/wolfsburg.ts
  web/ui/src/lib/clustersMap/campuses.generated.ts
  web/ui/src/lib/clustersMap/index.ts
  web/ui/src/lib/clustersMap/types.d.ts
  web/ui/src/lib/clustersMap/types.generated.d.ts
  web/ui/src/lib/clustersMap/utils.ts
  web/ui/src/lib/prototypes/string.js
  web/ui/src/lib/searchEngine.ts
  web/ui/src/pages/clusters/[campusSlug]/[clusterSlug].tsx
  web/ui/src/pages/clusters/index.tsx
  web/ui/src/types/globals.d.ts
  web/ui/tsconfig.json
  web/ui/yarn.lock
Labels: type/improvement ✨, state/confirmed 💜, priority/high 🟧, aspect/interface 🕹, domain/complex 🟧, size/XL, needs-preview-deploy

#531 feat(cluster): integrate 42 urduliz campus
  web/ui/src/lib/clustersMap/campus/urduliz.ts
  web/ui/src/lib/clustersMap/campuses.generated.ts
  web/ui/src/lib/clustersMap/types.generated.d.ts
Labels: size/M

#517 feat: add campus São Paulo
  web/ui/src/lib/clustersMap/campus/saoPaulo.ts
  web/ui/src/lib/clustersMap/campuses.generated.ts
  web/ui/src/lib/clustersMap/types.generated.d.ts
  web/ui/src/lib/prototypes/string.js
Labels: size/M

#535 fix: wrong alignment for wolfsburg
  web/ui/src/lib/clustersMap/campus/wolfsburg.ts
Labels: state/triage 🚦, size/M

#536 fix: react render comment on page title
  web/ui/src/containers/settings/SettingsLayout.tsx
  web/ui/src/pages/clusters/[campusSlug]/[clusterSlug].tsx
  web/ui/src/pages/friends/[groupSlug].tsx
Labels: size/S

#537 security: bump deps with vulnerabilities
  go.mod
  go.sum
Labels: size/M

#541 fix: incorrect title page of friendships
  web/ui/src/pages/friends/[groupSlug].tsx
Labels: priority/low 🟩, aspect/interface 🕹, domain/obvious 🟩, type/bug 🔥

#542 fix: loader on cluster search bar spin forever
  web/ui/src/components/Search/Search.tsx
  web/ui/src/containers/clusters/ClusterSidebar.tsx
Labels: state/triage 🚦, size/XS

#543 chore: upgrade to meilisearch v1.4.2
  deploy/stacks/apps/s42/meilisearch.tf
Labels: size/XS
